### PR TITLE
Adds a variable time step to runWorld

### PR DESCRIPTION
**Pull request by schell**
This references stuff talked about in #18

### CODE REVIEW

**Comment by ublubu** [comment]
I'll take some time to look this over to make sure the solution cache will still work. It's been a while, so I'm not sure, but my concern is that the solutions are impulse-based and therefore dependent on timestep. The actual cached values might not depend on time, though.

In the meantime, I'd like to avoid merge commits in the history. Can you rebase and also rename that "wip" commit?

**Comment by schell** [comment]
Yes, definitely. Also, afaik there is a "squash" merge that you can apply using github's UI. It does a rebase -i and squashes all commits into one.

**Comment by ublubu** [comment]
I had a look, and only the Baumgarte stabilization actually depends on the timestep. It does affect the value of the Lagrangian, which is the "solution" stored in the "solution cache".

For now, I'd like to officially support only fixed `dt`, since I haven't implemented a way to scale the cached Baumgarte stabilization (to account for a changing `dt`). However, you're free to have your own `stepWorld` and `runWorld` in your game code. The Baumgarte stabilization should have a small enough effect that your physics simulation should still look right.

**Comment by schell** [comment]
I'm actually using a fixed `dt` and accumulating the remainder in my physics tick, so that works with me. Can you expose (if you haven't already) the value of the `dt`?

**Comment by ublubu** [comment]
Sure. I'll put the constant stuff (contact behavior & timestep) in a reader, and then it'll be an argument to runEngineT. (https://github.com/ublubu/shapes/blob/d0d549b6d83bd2c9f757a7df111a2cfdaf62bebf/shapes/src/Physics/Solvers/Contact.hs#L47)

**Comment by schell** [comment]
Great! Thanks :)

**Pull request closed without merging**
